repos:
    - repo: https://github.com/LiquidFun/aoc_tiles
      rev: 0.7.2
      hooks:
          - id: aoc-tiles
            args:
                - --auto-add-tiles-to-git=amend
                - --language-sorting=py,go
                - --count-as-solved-when=either
                - --year-pattern=(?<!\d)(20[123]\d)-(?:py|go)(?=/)
                - --exclude-patterns=2025-py/**/*.py
